# config.yaml

model:
  g_conv_dim: 64 # Generator第一层卷积通道数
  d_conv_dim: 64 # Discriminator第一层卷积通道数
  g_repeat_num: 6 # Generator残差块数量
  d_repeat_num: 6 # Discriminator步长卷积层数
  lambda_cls: 1.0 # 分类损失权重
  lambda_rec: 10.0 # 重建损失权重
  lambda_gp: 10.0 # 梯度惩罚权重

training:
  batch_size: 1 # 批次大小 (batch_size: 2 占用16GB显存)
  # num_iters: 200000 # 总训练迭代次数
  # num_iters_decay: 100000 # 学习率衰减迭代次数
  num_iters: 10001 # [测试用] 总训练迭代次数
  num_iters: 10001 # [测试用] 总训练迭代次数
  num_iters_decay: 5000 # [测试用] 学习率衰减迭代次数
  autoencoder_lr: 0.0001 # Autoencoder学习率
  g_lr: 0.0001 # Generator学习率
  d_lr: 0.0001 # Discriminator学习率
  n_critic: 5 # Discriminator更新次数/Generator更新次数
  beta1: 0.5 # Adam beta1参数
  beta2: 0.999 # Adam beta2参数
  resume_iters: null # 恢复训练的迭代步数
  serial_batches: false # 是否按顺序取batch
  num_workers: 4 # 数据加载线程数
  test_interval: 1000  # 测试集评估迭代间隔

testing:
  test_iters: 200000 # test model from this step

data:
  trainCT_root: # 训练CT数据路径
    - ./data/volume_data/HuaXi/train
    - ./data/volume_data/ISLES_2018/train
  trainMR_root: # 训练MR数据路径
    - ./data/volume_data/HuaXi/train
    - ./data/volume_data/ISLES_2018/train
  testCT_root: # 测试CT路径
    - ./data/volume_data/HuaXi/test
    - ./data/volume_data/ISLES_2018/test
  testMR_root: # 测试MR路径
    - ./data/volume_data/HuaXi/test
    - ./data/volume_data/ISLES_2018/test
  file_pattern: '.*patient[A-Za-z]*\s*\d+_(ct|mr)\.npy'
  ct_file_pattern: '.*patient[A-Za-z]*\s*\d+_ct\.npy' # NEW
  mr_file_pattern: '.*patient[A-Za-z]*\s*\d+_mr\.npy' # NEW
  # file_pattern: 用于从文件名中提取病例ID的正则表达式模式，确保正确匹配和加载数据文件
  preload: true  # 将dataset直接加入内存
  max_depth: 29 # 数据最大切片数（深度）

directories:
  # starGAN
  log_dir: output/starGAN/metric_loss # 日志保存路径
  model_save_dir: output/starGAN/models # 模型保存路径
  sample_dir: output/starGAN/samples # 生成样本保存路径
  result_dir: output/starGAN/results # 生成结果保存路径
  # AutoEncoder
  autoencoder_log_dir: output/autoEncoder/metric_loss # Autoencoder模型保存路径
  autoencoder_model_save_dir: output/autoEncoder/models # Autoencoder模型保存路径
  autoencoder_sample_dir: output/autoEncoder/samples # Autoencoder生成样本保存路径
  autoencoder_result_dir: output/autoEncoder/results # Autoencoder生成结果保存路径

misc:
  mode: train # 运行模式 train 或 test
  use_tensorboard: true # 是否使用TensorBoard
  log_step: 10 # 日志记录间隔
  # sample_step: 1000 # 采样间隔
  sample_step: 100 # [测试用] 采样间隔
  model_save_step: 10000 # 模型保存间隔
  lr_update_step: 1000 # 学习率更新间隔

bugfree:
  bugfree_img_path: ./utils/bugfree_img/ # bugfree图片路径 (相对路径，相对于工作目录)
  img_name: buddha.bugfree # bugfree图片名称 # buddha.buggfree
  start_color: FF7EC7 # bugfree图片起始颜色
  end_color: FFED46 # bugfree图片结束颜色
